### ISSUE TITLE
Provider could cause a crash in race condition.

### ISSUE THREAD

**Issue by ccmjz** [samsao/DataProvider#5]
It need a method to nullifyDelegates

**Comment by GabrielCartier** [comment]
You got any time to actually work on this or fix it?

**Comment by ccmjz** [comment]
I'll find some time to fix it today.

**Comment by ccmjz** [comment]
I don't remember it clearly, but the case is like this: 
1. Try to do something being able to update the data source, such as load more at bottom, pull to refresh
2. Leave the view after provider received new data, but before finished the animation of update.
3. When provider trying to update cell view, it'll crash because the tableview is gone.

So we need a method to remove data source and delegate inside provider.

**Comment by GabrielCartier** [comment]
It was related to not nullifying the delegate properly. You need to force
it.

**Comment by AlexCrowe** [comment]
Ah, so it's not race condition then. I got it.

**Comment by GabrielCartier** [comment]
Yea it's a deallocation problem more
